name: Threadfin
version: "1.2.43"
slug: threadfin
description: Proxy M3U e gestor de EPG para Plex DVR, Emby e Jellyfin Live TV
url: https://github.com/Threadfin/Threadfin
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_network: true
webui: "http://[HOST]:34400/web/"
options:
  debug: 0
schema:
  debug: int(0,3)
